Console.WriteLine("Hey, welcome to my code!");
 Console.ReadKey();
 Console.WriteLine();
Console.WriteLine("I'm new here so there is almost nothing here...");
 Console.ReadKey();
 Console.WriteLine();
Console.WriteLine("Anyways, i can change color for you, here take a look!");
 Console.ReadKey();
 Console.WriteLine();
Console.ForegroundColor = ConsoleColor.Cyan;
Console.WriteLine("Hello, World!");
Console.WriteLine("It's better now, but look..");
 Console.ReadKey();
 Console.WriteLine();
Console.BackgroundColor = ConsoleColor.White;
Console.WriteLine("Hello, World!");
Console.WriteLine("Now it's brighter you see..");
 Console.ReadKey();
 Console.WriteLine();
Console.ForegroundColor= ConsoleColor.Black;
Console.WriteLine("Hello, World!");
Console.WriteLine("That's better i guess!");
 Console.ReadKey();
 Console.WriteLine();
Console.WriteLine("Hope you liked it, have a good one!");
